import{a as L,S as g,i as w}from"./assets/vendor-D_Kruy52.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const e of o)if(e.type==="childList")for(const u of e.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function s(o){const e={};return o.integrity&&(e.integrity=o.integrity),o.referrerPolicy&&(e.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?e.credentials="include":o.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function l(o){if(o.ep)return;o.ep=!0;const e=s(o);fetch(o.href,e)}})();const S="49130705-dcf2ba3ffc1780735e7549732",q="https://pixabay.com/api/",M=40;async function m(t,r=1){try{const s=await L.get(q,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:M}});return{images:s.data.hits,totalHits:s.data.totalHits}}catch{return{images:[],totalHits:0}}}new g(".gallery a");const c=document.querySelector(".loader");function p(t,r=!1){const s=document.querySelector(".gallery");r||(s.innerHTML="");const l=t.map(e=>`
        <li class = "list">
        <a href="${e.largeImageURL}" class="gallery-item">
            <img src="${e.webformatURL}" alt="${e.tags}">
            <ul class="info">
                <li>Likes<br>${e.likes}</li>
                <li>Views<br>${e.views}</li>
                <li>Comments<br>${e.comments}</li>
                <li>Downloads<br>${e.downloads}</li>
            </ul>
        </a></li>
    `).join("");s.insertAdjacentHTML("beforeend",l),new g(".gallery a").refresh()}function a(){w.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}function h(){c&&(c.style.display="block")}function d(){c&&(c.style.display="none")}let i=1,y="";const n=document.querySelector(".load-more");n.style.display="none";document.querySelector(".search-form").addEventListener("submit",async function(t){t.preventDefault();const r=t.target.elements.searchQuery.value.trim();if(!r){a();return}r!==y&&(i=1,y=r,document.querySelector(".gallery").innerHTML="",n.style.display="none",E()),h();try{const{images:s,totalHits:l}=await m(r,i);d(),s.length>0?(p(s,!1),l>i*40?n.style.display="block":(n.style.display="none",f()),b()):(a(),n.style.display="none")}catch{d(),a()}});n.addEventListener("click",async function(){i+=1,h();try{const{images:t,totalHits:r}=await m(y,i);d(),t.length>0?(p(t,!0),r<=i*40?(n.style.display="none",f()):b()):(n.style.display="none",f())}catch{d(),a()}});const b=()=>{const t=document.querySelector(".gallery .gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}};function f(){const t=document.querySelector(".end-message");t.style.display="block"}function E(){const t=document.querySelector(".end-message");t.style.display="none"}
//# sourceMappingURL=index.js.map
