import{a as b,S as L,i as w}from"./assets/vendor-D_Kruy52.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();const S="49130705-dcf2ba3ffc1780735e7549732",q="https://pixabay.com/api/",M=40;async function g(e,r=1){try{const t=await b.get(q,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:M}});return{images:t.data.hits,totalHits:t.data.totalHits}}catch{return{images:[],totalHits:0}}}const E=new L(".gallery a"),c=document.querySelector(".loader");function m(e){const r=document.querySelector(".gallery");r.innerHTML=e.map(t=>`
        <li class = "list">
        <a href="${t.largeImageURL}" class="gallery-item">
            <img src="${t.webformatURL}" alt="${t.tags}">
            <ul class="info">
                <li>Likes<br>${t.likes}</li>
                <li>Views<br>${t.views}</li>
                <li>Comments<br>${t.comments}</li>
                <li>Downloads<br>${t.downloads}</li>
            </ul>
        </a></li>
    `).join(""),E.refresh()}function a(){w.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}function p(){c&&(c.style.display="block")}function u(){c&&(c.style.display="none")}let i=1,y="";const n=document.querySelector(".load-more");n.style.display="none";document.querySelector(".search-form").addEventListener("submit",async function(e){e.preventDefault();const r=e.target.elements.searchQuery.value.trim();if(!r){a();return}r!==y&&(i=1,y=r,document.querySelector(".gallery").innerHTML="",n.style.display="none",P()),p();try{const{images:t,totalHits:l}=await g(r,i);u(),t.length>0?(m(t),l>i*40?n.style.display="block":(n.style.display="none",f()),h()):a()}catch{u(),a()}});n.addEventListener("click",async function(){i+=1,p();try{const{images:e,totalHits:r}=await g(y,i);u(),e.length>0?(m(e,!0),r<=i*40?(n.style.display="none",f()):h()):(n.style.display="none",f())}catch{u(),a()}});const h=()=>{const e=document.querySelector(".gallery .gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}};function f(){const e=document.querySelector(".end-message");e.style.display="block"}function P(){const e=document.querySelector(".end-message");e.style.display="none"}
//# sourceMappingURL=index.js.map
